fix ci

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -35,9 +35,25 @@ runs:
 
     - name: Install Dataiku Python API
       run: |
+        echo "Downloading Dataiku Python API from ${{ inputs.dataiku_instance_a_url }}"
         curl -k -o dataiku.zip ${{ inputs.dataiku_instance_a_url }}/public/api/packages/dataiku.zip
+        if [ $? -ne 0 ]; then
+          echo "Failed to download Dataiku Python API package"
+          exit 1
+        fi
+        echo "Downloaded Dataiku Python API package"
         unzip dataiku.zip -d dataiku
+        if [ $? -ne 0 ]; then
+          echo "Failed to unzip Dataiku Python API package"
+          exit 1
+        fi
+        echo "Unzipped Dataiku Python API package"
         python -m pip install ./dataiku
+        if [ $? -ne 0 ]; then
+          echo "Failed to install Dataiku Python API"
+          exit 1
+        fi
+        echo "Installed Dataiku Python API"
       shell: bash
 
     - name: Run Dataiku GitOps Action
